name: Check

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  check-windows:
    name: Check ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: i686 Windows
            image: windows-latest
            msystem: MINGW32
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: git
          pacboy: >-
            gcc:p
            freetype:p
            harfbuzz:p
            rust:p
            ca-certificates

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.msystem }}
      - shell: msys2 {0}
        run: cargo clippy --workspace --exclude sbr-overlay --all-features -- -D warnings
      - shell: msys2 {0}
        run: ./ci/c_sanity_check.sh
